apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.imageName }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: APP_PORT
              value: "{{ .Values.port }}"
            - name: INFLUXDB_ORGANIZATION
              value: "{{ .Values.influxdb.organization }}"
            - name: INFLUXDB_BUCKET
              value: "{{ .Values.influxdb.bucket }}"
            - name: INFLUXDB_ADDRESS
              value: "{{ .Values.influxdb.address }}"
            - name: INFLUXDB_TOKEN
              value: "{{ .Values.influxdb.token }}"
          ports:
            - protocol: TCP
              containerPort: {{ .Values.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
